version: '0.1'

services:
  app:
    build: .
    image: develfood
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/develfood
      - SPRING_DATASOURCE_USERNAME=develfood
      - SPRING_DATASOURCE_PASSWORD=develfood
    networks:
      - app-network
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: develfood
      POSTGRES_PASSWORD: develfood
      POSTGRES_USER: develfood
    networks:
      - app-network
    ports:
      - '5432:5432'

networks:
  app-network:
    driver: bridge
