spring:
  application:
    name: develfood
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/develfood
    username: develfood
    password: develfood
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
server:
  error:
    include-stacktrace: never

