CREATE TABLE restaurant_promotions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   restaurant_id BIGINT NOT NULL,
   name VARCHAR(255) NOT NULL,
   percent FLOAT NOT NULL,
   initial_date date,
   final_date date,
   CONSTRAINT pk_restaurant_promotions PRIMARY KEY (id)
);

ALTER TABLE restaurant_promotions ADD CONSTRAINT FK_RESTAURANT_PROMOTIONS_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurants (id);