CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(50) NOT NULL,
   last_name VARCHAR(150) NOT NULL,
   photo_url VARCHAR(255),
   cpf CHAR(11) NOT NULL,
   phone VARCHAR(18) NOT NULL,
   user_id BIGINT NOT NULL,
   address_id BIGINT,
   CONSTRAINT pk_customers PRIMARY KEY (id)
);

ALTER TABLE customers ADD CONSTRAINT uc_customers_user UNIQUE (user_id);

ALTER TABLE customers ADD CONSTRAINT FK_CUSTOMERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE customers ADD CONSTRAINT uc_customers_address UNIQUE (address_id);

ALTER TABLE customers ADD CONSTRAINT fk_customers_on_address FOREIGN KEY (address_id) REFERENCES addresses (id);